name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 21 * * 1,4" # 매주 월/목 오전 6시 KST (UTC 21:00)
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Supabase SDK
        run: npm install @supabase/supabase-js --force

      - name: Call Supabase RPC function
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          node -e "
          (async () => {
            try {
              const { createClient } = require('@supabase/supabase-js');
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

              const { data, error } = await supabase.rpc('get_workload_allocation_ranges');

              if (error) throw error;

              console.log('✅ RPC 호출 성공: get_workload_allocation_ranges');
              console.log('반환된 행 수:', data.length);
            } catch (err) {
              console.error('❌ RPC 호출 실패:', err.message);
              process.exit(1);
            }
          })();
          "
