name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 21 * * 1,4" # 매주 월/목 오전 6시 KST (UTC 21:00)
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Supabase SDK
        run: npm install @supabase/supabase-js --force

      - name: Ping Supabase with visible query
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: |
          node -e "
          (async () => {
            try {
              const { createClient } = require('@supabase/supabase-js');
              const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

              const { data, count, error } = await supabase
                .from('resources')
                .select('id', { count: 'exact' })
                .order('date_only', { ascending: false })
                .order('hour_of_day', { ascending: false })
                .limit(10);


              if (error) throw error;

              console.log('Supabase keep-alive ping 성공 ✅');
              console.log('Returned rows:', data.length);
              console.log('Row count:', count);
            } catch (err) {
              console.error('❌ Supabase ping 실패:', err.message);
              process.exit(1);
            }
          })();
          "
